### ISSUE TITLE
Doesn't show multiple codepoints of combined chars.

### ISSUE THREAD

**Issue by YPetremann** [medo64/Code-Point#3]
Actually when your are placed under a combined char like this one 🇬🇧 it report U+1F1EC but should report U+1F1EC U+1F1E7

**Comment by medo64** [comment]
Thanks for reporting this. Fixed in version 1.5.0.

**Comment by YPetremann** [comment]
Just a thought, I don't know if it's possible to know the next valid cursor position and previous valid cursor position, because that would simplify the algorithm and let vscode do the job, from current cursor position, get the next valid cursor position, then from this last get the previous cursor position (this would prevent case where cursor is in the middle of a char), then copy everything between the two positions and report back on the statusbar

I know that a hacky way but for example family combined chars like 👩‍❤️‍💋‍👨 U+1F469 U+200D U+2764 U+FE0F U+200D U+1F48B U+200D U+1F468 are far more complex to parse and it would be preferable to interpret based on what seems valid for vscode

**Comment by medo64** [comment]
Unfortunately, I haven't found a way to do that trickery :(
Both VSCode and JavaScript seem to be a bit lacking there. Thank you for example, I will try to figure something that will cover more combining characters.

**Comment by medo64** [comment]
Thank you for test files!
I believe 1.5.2 sorts that out.
