### ISSUE TITLE
Skin Tone Selector Support

### ISSUE THREAD

**Issue by doraTeX** [medo64/Code-Point#7]
Codepoints of an emoji including a Skin Tone Selector are not displayed correctly in `v1.8.0`.

# Examples
## Emoji not including a Skin Tone Selector (works correctly)
* Input: `🙋‍♂️`
* Output: 

![image](https://user-images.githubusercontent.com/6186180/149928641-32c386e0-ddd3-4dd7-b6ca-34bc37ccdba0.png)

## Emoji including a Skin Tone Selector
* Input: `🙋🏻‍♂️`
* Output:

![image](https://user-images.githubusercontent.com/6186180/149928872-42da00db-67db-4170-8149-74fbc51ee1da.png)

* Expected result:
```
U+1F64B	HAPPY PERSON RAISING ONE HAND
U+1F3FB	EMOJI MODIFIER FITZPATRICK TYPE-1-2
U+200D	ZERO WIDTH JOINER
U+2642	MALE SIGN
U+FE0F	VARIATION SELECTOR-16
```

**Comment by medo64** [comment]
Thanks! Should be fixed in 1.8.1 arriving shortly.
